mvc/controllers/AgenciaController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\TipoUsuario;
//************actualizar***************
use app\models\Agencia\ActualizarChoferModel;
use app\models\Agencia\ActualizarRecepcionistaModel;
use app\models\Agencia\ActualizarVehiculoAgenciaModel;
//use app\models\Agencia\ActualizarVehiculoAgenciaModel;
//use app\models\Agencia\ActualizarVehiculoAgenciaModel;
//************alta***************
use app\models\Agencia\AltaVehiculoAgenciaModel;
use app\models\Agencia\AltaRecepcionistaAgenciaModel;
use app\models\Agencia\AltaChoferAgenciaModel;
//************listar***************
use app\models\Agencia\ListaChoferesModel;
use app\models\Agencia\ListaRecepcionistasModel;
use app\models\Agencia\ListaVehiculoModel;
use app\models\Agencia\ListaViajesTurnoManianaModel;
use app\models\Agencia\ListadoCalificacionesModel;
use app\models\Agencia\ListadoViajesModel;
use app\models\Agencia\ViajesGridModel;
use app\models\Agencia\GridModel;

class AgenciaController extends Controller {

    public $layout = 'mainAgencia';                           //se asocia al layout predeterminado

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'alta_vehiculo_agencia','alta_vehiculo_agencia', 'alta_chofer_agencia', 'alta_telefonista_agencia', 'actualizar_vehiculo_agencia','actualizar_chofer_agencia','actualizar_recepcionista_agencia','listar_choferes_agencia','listar_recepcionistas_agencia','listar_vehiculo_agencia','listado_calificaciones','listado_viajes'], //solo debe aplicarse a las acciones login, logout , admin,recepcionista, chofer y cliente. Todas las demas acciones no estan sujetas al control de acceso
                'rules' => [                              //reglas
                    //el administrador tiene permisos sobre las siguientes acciones
                    ['actions' => ['index', 'alta_vehiculo_agencia','alta_vehiculo_agencia', 'alta_chofer_agencia', 'alta_telefonista_agencia', 'actualizar_vehiculo_agencia','actualizar_chofer_agencia','actualizar_recepcionista_agencia','listar_choferes_agencia','listar_recepcionistas_agencia','listar_vehiculo_agencia','listado_calificaciones','listado_viajes'],
                        'allow' => true,
                        'roles' => ['@'], //El arroba es para el usuario autenticado
                        'matchCallback' => function ($rule, $action) {                    //permite escribir la l?gica de comprobaci?n de acceso arbitraria, las paginas que se intentan acceder solo pueden ser permitidas si es un...
                    return TipoUsuario::usuarioAdministrador(Yii::$app->user->identity->RolID);
                    //Llamada al m?todo que comprueba si es un administrador
                    //Retorno el metodo del modelo que comprueba el tipo de usuario que es por el rol (1,2,3,4) etc y que devuelve true o false
                }
                    ]
                ]
            ]
        ];
    }

    public function actions() {

        if (!Yii::$app->user->isGuest) {                                                                              //si el usuario esta logeado, o sea no es invitado
            if (Yii::$app->user->identity->RolID == 1) {                                                                //si el usuario es administrador
                Yii::$app->errorHandler->errorAction = 'agencia/error';                                               //se muestra la pantalla de error de agencia y su respectivo layout
            } elseif (Yii::$app->user->identity->RolID == 2) {
                Yii::$app->errorHandler->errorAction = 'recepcionista/error';
            } elseif (Yii::$app->user->identity->RolID == 3) {
                Yii::$app->errorHandler->errorAction = 'chofer/error';
            } elseif (Yii::$app->user->identity->RolID == 4) {
                Yii::$app->errorHandler->errorAction = 'cliente/error';
            } else {
                Yii::$app->errorHandler->errorAction = 'site/error';
            }
        } else {                                                                                                      //sino (si el usuario es invitado) se muestra la pagina de error del site
            Yii::$app->errorHandler->errorAction = 'site/error';
        }
        //la ruta ya esta harcodeada en config/web en la parte errorHandler
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {                      //renderiza el index de la carpeta agencia dentro de views
        return $this->render('index');
    }

//*************************************************************************//
    //******************************Alta**************************************//

    public function actionAlta_vehiculo_agencia() {
        $model = new AltaVehiculoAgenciaModel();
        if ($model->load(Yii::$app->request->post()) && ($model->registrarvehiculo() === true)) {
            Yii::$app->session->setFlash('vehiculo creado con exito');
            return $this->redirect(['agencia/listar_vehiculo_agencia']);
        }
        return $this->renderAjax("altaVehiculo", ['model' => $model]);
    }

    public function actionAlta_chofer_agencia() {
        $model = new AltaChoferAgenciaModel();
        if ($model->load(Yii::$app->request->post()) && ($model->registrarchofer() === true)) {
            Yii::$app->session->setFlash('Chofer creado con exito');
            return $this->redirect(['agencia/listar_choferes_agencia']);
        }
        return $this->renderAjax("altaChofer", ['model' => $model]);
    }

    public function actionAlta_telefonista_agencia() {
        $model = new AltaRecepcionistaAgenciaModel();
        if ($model->load(Yii::$app->request->post()) && ($model->registrarrecepcionista() === true)) {
            Yii::$app->session->setFlash('Recepcionista creado con exito');
            return $this->redirect(['agencia/listar_recepcionistas_agencia']);
        }
        return $this->renderAjax("altaTelefonista", ['model' => $model]);
    }

    //**************************************************************************//
    //******************************Actualizacion**************************************//

    public function actionActualizar_vehiculo_agencia() {
        if (isset(Yii::$app->session['actualizar'])) {
            $param = Yii::$app->session['actualizar'];
        }
        else {
            $param = null;
        }

        $model = new ActualizarVehiculoAgenciaModel();
        if ($model->load(Yii::$app->request->post()) && ($model->modificarvehiculo($param['VehiculoID']) === true)) {
            Yii::$app->session->setFlash('Vehiculo actualizado con exito');
            return $this->redirect(['agencia/listar_vehiculo_agencia']);
        }
        $model->setvehiculo($param);
        return $this->renderAjax("actualizarVehiculo", ['model' => $model]);
    }

    public function actionActualizar_chofer_agencia() {
        if (isset(Yii::$app->session['actualizar'])) {
            $param = Yii::$app->session['actualizar'];
        }
        else {
            $param = null;
        }
        $model = new ActualizarChoferModel();

        if ($model->load(Yii::$app->request->post()) && ($model->modificarchofer($param['PersonaID']) === true)) {
            Yii::$app->session->setFlash('Chofer actualizado con exito');
            return $this->redirect(['agencia/listar_choferes_agencia']);
        }
        $model->setchofer($param);
        return $this->renderAjax("actualizarChofer", ['model' => $model]);
    }

    public function actionActualizar_recepcionista_agencia() {
        if (isset(Yii::$app->session['actualizar'])) {
            $param = Yii::$app->session['actualizar'];
        }
        else {
            $param = null;
        }
        $model = new ActualizarRecepcionistaModel();
        if ($model->load(Yii::$app->request->post()) && ($model->modificarrecepcionista($param['PersonaID']) === true)) {
            Yii::$app->session->setFlash('Recepcionista actualizado con exito');
            return $this->redirect(['agencia/listar_recepcionistas_agencia']);
        }
        $model->setrecepcionista($param);
        return $this->render("actualizarRecepcionista", ['model' => $model]);
    }
    //**************************************************************************//
    //******************************Listar**************************************//

    public function actionListar_choferes_agencia() {
        $model = new GridModel();
        $model->setDataProviderChofer();
        if (\Yii::$app->request->isPost)  {
            if (\Yii::$app->request->isAjax) {
            switch (\Yii::$app->request->post('operaciones')){
                case 'actualizar':
                $selection=(array)Yii::$app->request->post('keylist');
                $personaselected=$model->dataProvider->allModels[$selection[0]];
                Yii::$app->session['actualizar'] = $personaselected;
                break;

                case 'eliminar':
                $selection =(array)Yii::$app->request->post('keylist');
                $personaSelected = $model->dataProvider->allModels[$selection[0]];
                $model->eliminarEmpleado($personaSelected);
                Yii::$app->session->setFlash('Chofer eliminado con exito');
                return $this->refresh();
            }
          }
        }
        return $this->render("listaChoferes", ['model' => $model]);
    }

    public function actionListar_recepcionistas_agencia() {
        $model = new GridModel();
        $model->setDataProviderrecepcionista();
        if (\Yii::$app->request->isPost)  {
            if (\Yii::$app->request->isAjax) {
                switch (\Yii::$app->request->post('operaciones')){

mvc/controllers/ClienteController.php
<?php

namespace app\controllers;

use app\models\Usuario\SolicitudRemiseriaModel;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\TipoUsuario;
use app\models\Usuario\PSFormularioSolicitudRegistrarAgenciaModel;
use app\models\Usuario\PSFormularioSolicitarServcioRemiseriaModel;
use app\models\Usuario\ListaHistorialViajesUsuarioModel;
use app\models\Usuario\ListaHistorialCalificacionesUsuarioModel;
use app\models\Usuario\CalificacionServicioModel;
use app\models\Agencia\ViajesGridModel;
use app\models\Agencia\GridModel;
use app\controllers\PusherController;
use yii\helpers\Url;

class ClienteController extends Controller {

    public $layout = 'mainCliente';                                             //se asocia al layout predeterminado
    

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','Lista_historial_calificaciones','Calificar_servicio', 'Lista_historial_viajes'], //solo debe aplicarse a las acciones login, logout , admin,recepcionista, chofer y cliente. Todas las demas acciones no estan sujetas al control de acceso
                'rules' => [                              //reglas
                    //el administrador tiene permisos sobre las siguientes acciones
                    ['actions' => ['index','Lista_historial_calificaciones','Calificar_servicio', 'Lista_historial_viajes'],
                        'allow' => true,
                        'roles' => ['@'], //El arroba es para el usuario autenticado
                        'matchCallback' => function ($rule, $action) {                    //permite escribir la l?gica de comprobaci?n de acceso arbitraria, las paginas que se intentan acceder solo pueden ser permitidas si es un...
                    return TipoUsuario::usuarioCliente(Yii::$app->user->identity->RolID);
                    //Llamada al m?todo que comprueba si es un administrador
                    //Retorno el metodo del modelo que comprueba el tipo de usuario que es por el rol (1,2,3,4) etc y que devuelve true o false
                }
                    ]
                ]
            ]
        ];
    }

    public function actions() {
        if (!Yii::$app->user->isGuest) {                                                                              //si el usuario esta logeado, o sea no es invitado
            if (Yii::$app->user->identity->RolID == 1) {                                                                //si el usuario es administrador
                Yii::$app->errorHandler->errorAction = 'agencia/error';                                               //se muestra la pantalla de error de agencia y su respectivo layout
            } elseif (Yii::$app->user->identity->RolID == 2) {
                Yii::$app->errorHandler->errorAction = 'recepcionista/error';
            } elseif (Yii::$app->user->identity->RolID == 3) {
                Yii::$app->errorHandler->errorAction = 'chofer/error';
            } elseif (Yii::$app->user->identity->RolID == 4) {
                Yii::$app->errorHandler->errorAction = 'cliente/error';
            } else {
                Yii::$app->errorHandler->errorAction = 'site/error';
            }
        } else {                                                                                                      //sino (si el usuario es invitado) se muestra la pagina de error del site
            Yii::$app->errorHandler->errorAction = 'site/error';
        }
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        $model = new SolicitudRemiseriaModel();
        $info = Yii::$app->user->identity->PersonaID;

        if ($model->load(Yii::$app->request->post()) && ($model->GuardarViaje() === true)) {
            Yii::$app->pusher->triggerEvent($model->idAgencia,'solicitudNueva','un mensaje');
            Yii::$app->session['channel'] = $model->idAgencia;
            //$data['message'] = 'hello world';
            //$pusher->trigger('my_channel', 'my_event', $data);
            return $this->redirect(['lista_historial_viajes']);
        }
        return $this->render("index", ['model' => $model]);
    }
    /*
    public function actionCalificar_servicio() {
        $model = new CalificacionServicioModel();
        if ($model->load(Yii::$app->request->post()) && ($model->setCalificacion() === true))
        {
            Yii::$app->session->setFlash('calificacionSeteada');
            return $this->redirect(['listarHistorialCalificaciones']);
        }
        else{
            if (isset(Yii::$app->session['actualizar'])) {
                $viajeSelected = Yii::$app->session['actualizar'];
                $model->setUpdateInfo($viajeSelected);
            }
            else {
                $viajeSelected = null;
            }
            //$selection=(array)Yii::$app->request->post('keylist');

            return $this->renderAjax("calificarServicio", ['model' => $model]);
        }
    }*/

    public function actionLista_historial_calificaciones() {
        $model = new ListaHistorialCalificacionesUsuarioModel();
        $model->setDataProvider();
        return $this->render("listaHistorialCalificaciones", ['model' => $model]);
    }

    public function actionCalificar_servicio() {

        if (isset(Yii::$app->session['actualizar']))
        {
            $viajeSelected = Yii::$app->session['actualizar'];
        }
        else {
            $viajeSelected = null;
        }
        $model = new CalificacionServicioModel();
        if ($model->load(Yii::$app->request->post()) && ($model->setCalificacion($viajeSelected) === true)) {
            Yii::$app->session->setFlash('Calificacion Exitosa');
            return $this->redirect(['cliente/lista_historial_calificaciones']);
            }
        $model->setUpdateInfo($viajeSelected);
        return $this->renderAjax("calificarServicio", ['model' => $model]);
    }

    public function actionLista_historial_viajes() {
        $model = new ListaHistorialViajesUsuarioModel();
        $info = Yii::$app->session['channel'].";" .Yii::$app->user->identity->PersonaID;
        $model->setDataProvider();
        if (\Yii::$app->request->isPost)  {
            if (\Yii::$app->request->isAjax) {
                $selection=(array)Yii::$app->request->post('keylist');
                $personaselected=$model->dataProvider->allModels[$selection[0]];
                Yii::$app->session['actualizar'] = $personaselected;

            }
            //else{}*/
        }
        return $this->render("listaHistorialViajes", ['model' => $model,'socketInfo'=> $info]);
    }

    /*
    public function actionCerrarViaje() {                      //renderiza el index de la carpeta agencia dentro de views
      $model = new ListaHistorialViajesUsuarioModel();
      $model->cerrarViaje();
      return $this->renderAjax("listaHistorialViajes", ['model' => $model]);
      }*/
}

mvc/views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\models\TipoUsuario;
use app\assets\BootswatchAsset;
use yii\helpers\Url;

BootswatchAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <meta charset="<?= Yii::$app->charset ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <?= Html::csrfMetaTags() ?>
        <title>
            <?= Html::encode($this->title) ?>
        </title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php
        $this->beginBody();
        /* include('testMaps.php'); */
        ?>
        <div class="wrap" >
            <?php
            NavBar::begin([
                'brandLabel' => '<img src="img/LogoApp.png" style="display:inline; margin-top: -20px; vertical-align: top; width:120px; height:55px;">',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => ['class' => 'navbar navbar-default navbar-fixed-top navbar-transparent'],
                    //'options' => [
                    //   'class' => 'navbar-inverse navbar-fixed-top',
                    //],
            ]);
            ;

            echo Nav::widget([
                'encodeLabels' => false,
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    ['label' => '<span class="fa fa-home"></span> ' . Html::encode('Home'), 'url' => ['/site/index']],
                    ['label' => '<span class="fa fa-users"></span> ' . Html::encode('Quiénes Somos'), 'url' => ['/site/about']],
                    ['label' => '<span class="fa fa-comment-o"></span> ' . Html::encode('Contactarnos'), 'url' => ['/site/contact']],
                    ['label' => '<span class="fa fa-user-plus"></span> ' . Html::encode('Registrar'),
                        'items' => [
                            ['label' => '<span class="fa fa-user"></span> ' . Html::encode('Usuario'), 'url' => ['/site/registro'],],
                            '<li class="divider"></li>',
                            ['label' => '<span class="fa fa-industry"></span> ' . Html::encode('Remiseria'), 'url' => ['/site/solicitud_registrar_agencia'],],
                        ],],
                    Yii::$app->user->isGuest ? (
                            ['label' => '<span class="fa fa-sign-in"></span> ' . Html::button('Login', ['value' => Url::toRoute('/site/login'), 'class' => 'btn btn-primary', 'id' => 'modalButtonLogin', 'style' => 'background-color:#4e5d6c;margin-top:-5px;font-size:13px;'])]

                            ) : (
                            '<li>'
                            . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                            . Html::submitButton(
                                    'Logout (' . Yii::$app->user->identity->Usuario . ')', ['class' => 'btn btn-link']
                            )
                            . Html::endForm()
                            . '</li>'
                            )
                ],
            ]);
            NavBar::end();
            ?>

            <?=
            Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ])
            ?>
            <?= $content ?>
        </div>

        <footer class="footer">
            <div class="container">
                <!--<hr style="border:1px solid gray;">-->

                <span id="footer-copy-right" style="text-align:center"> 
                    <i class="fa fa-map-marker"></i>   Contactenos:&nbsp; &nbsp; &nbsp; &nbsp;
                    <i class="fa fa-phone-square"></i> &nbsp; 011-4369-4657 &nbsp; &nbsp; 011-4287-5324 &nbsp; &nbsp;
                    <i class="fa fa-envelope"></i> &nbsp; administracion@remisya.com
                </span>
            </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

mvc/views/layouts/mainAgencia.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\assets\BootswatchAsset;

BootswatchAsset::register($this);
AppAsset::register($this);


$this->title = 'Agencia';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
        <meta charset="<?= Yii::$app->charset ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <?= Html::csrfMetaTags() ?>
        <title>
            <?= Html::encode($this->title) ?>
        </title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php
        $this->beginBody();
        /* include('testMaps.php'); */
        ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => '<img src="img/LogoApp.png" style="display:inline; margin-top: -20px; vertical-align: top; width:120px; height:55px;">&nbsp&nbsp&nbsp&nbsp<b styel="size:15px">Agencia</b>',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => ['class' => 'navbar navbar-default navbar-fixed-top navbar-transparent'],
            ]);
            ;
            echo Nav::widget([
                'encodeLabels' => false,
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    ['label' => '<span class="fa fa-home"  ></span> ' . Html::encode('Home'), 'url' => ['/agencia/index']],
                    [
                        'label' => '<span class="fa fa-user-plus"></span> ' . Html::encode('Choferes'),
                        'items' => [
                            ['label' => '<span class="fa fa-th-list"></span> ' . Html::encode('Administrar'), 'url' => ['/agencia/listar_choferes_agencia'], 'data-toggle' => 'dropdown', 'class' => 'dropdown-toggle'],
                        ],
                    ],
                    [
                        'label' => '<span class="fa fa-user-plus"></span> ' . Html::encode('Telefonistas'),
                        'items' => [
                            ['label' => '<span class="fa fa-th-list"></span> ' . Html::encode('Administrar'), 'url' => ['/agencia/listar_recepcionistas_agencia'], 'data-toggle' => 'dropdown', 'class' => 'dropdown-toggle'],
                        ],
                    ],
                    [
                        'label' => '<span class="fa fa-plus"  ></span> ' . Html::encode('Vehiculos'),
                        'items' => [
                            ['label' => '<span class="fa fa-th-list"></span> ' . Html::encode('Administrar'), 'url' => ['/agencia/listar_vehiculo_agencia'], 'data-toggle' => 'dropdown', 'class' => 'dropdown-toggle'],
                        ],
                    ],
                    [
                        'label' => '<span class="fa fa-star"  ></span> ' . Html::encode('Calificaciones'),
                        'items' => [
                            ['label' => '<span class="fa fa-th-list"></span> ' . Html::encode('Administrar'), 'url' => ['/agencia/listado_calificaciones'], 'style' => 'background-color:blue;', 'class' => 'dropdown-toggle'],
                        ],
                    ],
                    [
                        'label' => '<span class="fa fa-suitcase"  ></span> ' . Html::encode('Viajes'),
                        'items' => [
                            ['label' => '<span class="fa fa-th-list"></span> ' . Html::encode('Administrar'), 'url' => ['/agencia/listado_viajes'], 'style' => 'background-color:blue;', 'class' => 'dropdown-toggle'],
                        ],
                    ],
                    Yii::$app->user->isGuest ? (
                            ['label' => 'Login', 'url' => ['/site/login']]
                            ) : (
                            '<li>'
                            . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                            . Html::submitButton(
                                    'Logout (' . Yii::$app->user->identity->Usuario . ')', ['class' => 'btn btn-link']
                            )
                            . Html::endForm()
                            . '</li>'
                            )
                ],
            ]);
            NavBar::end();
            ?>


            <!--<div class="container">-->
            <?=
            Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ])
            ?>
            <?= $content ?>
            <!--</div>-->
        </div>


        <footer class="footer">
            <div class="container">
                <span id="footer-copy-right" style="text-align:center"> 
                    <i class="fa fa-map-marker"></i>   Contactenos:&nbsp; &nbsp; &nbsp; &nbsp;
                    <i class="fa fa-phone-square"></i> &nbsp; 011-4369-4657 &nbsp; &nbsp; 011-4287-5324 &nbsp; &nbsp;
                    <i class="fa fa-envelope"></i> &nbsp; administracion@remisya.com
                </span>
            </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

mvc/views/layouts/mainCliente.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\models\TipoUsuario;
use app\assets\AppAssetCliente;
use app\assets\AppAssetWebSite;
use app\assets\BootswatchAsset;

BootswatchAsset::register($this);
AppAssetCliente::register($this);

$this->title = 'Usuario';
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" />
        <meta charset="<?= Yii::$app->charset ?>" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <?= Html::csrfMetaTags() ?>
        <title>
            <?= Html::encode($this->title) ?>
        </title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php
        $this->beginBody();
        /* include('testMaps.php'); */
        ?>
        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => '<img src="img/LogoApp.png" style="display:inline; margin-top: -20px; vertical-align: top; width:120px; height:55px;">&nbsp&nbsp&nbsp&nbsp<b styel="size:15px">Usuario</b>',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => ['class' => 'navbar navbar-default',]
                    //'options' => [
                    //    'class' => 'navbar-inverse navbar-fixed-top',
                    //],
            ]);
            ;
            echo Nav::widget([
                'encodeLabels' => false,
                'options' => ['class' => 'nav-pills navbar-right'],
                'items' => [
                    ['label' => '<span class="fa fa-car"></span> ' . Html::encode('Solicitar Servicio'), 'url' => ['/cliente/index']],
                    ['label' => '<span class="fa fa-suitcase"></span> ' . Html::encode('Viajes'),
                        'items' => [
                            ['label' => '<span class="fa fa-th-list"></span> ' . Html::encode('Ver Historial'), 'url' => ['/cliente/lista_historial_viajes'],],
                     ],
                    ],
                    ['label' => '<span class="fa fa-star"></span> ' . Html::encode('Calificaciones'), 'items' => [
                            ['label' => '<span class="fa fa-th-list"></span> ' . Html::encode('Ver Historial'), 'url' => ['/cliente/lista_historial_calificaciones'],],
                        ],
                    ],

                    Yii::$app->user->isGuest ? (
                            //['label' => 'Login', 'url' => ['/site/login'], 'id'=>'btn-login','onClick()'=>'abrirLoginDesdeBotonLoginHeader()']
                            ['label' => 'Login', 'url' => ['/site/login']]
                            ) : (
                            '<li>'
                            . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                            . Html::submitButton(
                                    'Logout (' . Yii::$app->user->identity->Usuario . ')', ['class' => 'btn btn-link']
                            )
                            . Html::endForm()
                            . '</li>'
                            )
                ],
            ]);
            NavBar::end();
            ?>
                <?=
                Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
                ?>
                <?= $content ?>
     </div>

        <footer class="footer">
            <div class="container">          
                <i class="fa fa-map-marker"></i>   Contactenos:&nbsp; &nbsp; &nbsp; &nbsp;
                <i class="fa fa-phone-square"></i> &nbsp; 011-4369-4657 &nbsp; &nbsp; 011-4287-5324 &nbsp; &nbsp;
                <i class="fa fa-envelope"></i> &nbsp; administracion@remisya.com           
            </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>