mvc/controllers/RecepcionistaController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\TipoUsuario;
use app\models\Recepcionista\AltaViajeManualModel;
use app\models\Recepcionista\ActualizarViajeModel;
use app\models\Recepcionista\AutorizarSolicitudModel;
use app\models\Recepcionista\ListaSolicitudesServicioModel;
use app\models\Recepcionista\ListaSolicitudesOnlineModel;
use app\models\Recepcionista\AltaClienteModel;
use app\models\Recepcionista\ActualizarClienteModel;
use app\models\Recepcionista\AltaTarifaModel;
use app\models\Recepcionista\EliminarTarifaModel;
use app\models\Recepcionista\ActualizarTarifaModel;
use app\models\Recepcionista\AdministrarClienteModel;
use app\models\Recepcionista\AdministrarTarifaModel;
use yii\web\Response;
use yii\db\Query;
use yii\widgets\ActiveForm;

class RecepcionistaController extends Controller {

    public $layout = 'mainRecepcionista';                           //se asocia al layout predeterminado

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index'], //solo debe aplicarse a las acciones login, logout , admin,recepcionista, chofer y cliente. Todas las demas acciones no estan sujetas al control de acceso
                'rules' => [                              //reglas
                    //el administrador tiene permisos sobre las siguientes acciones
                    ['actions' => ['index', 'alta_viaje_manual', 'actualizarviaje', 'listaviajes', 'listasolicitudes', 'autorizarsolicitud', 'clienteslist'],
                        'allow' => true,
                        'roles' => ['@'], //El arroba es para el usuario autenticado
                        'matchCallback' => function ($rule, $action) {                    //permite escribir la l?gica de comprobaci?n de acceso arbitraria, las paginas que se intentan acceder solo pueden ser permitidas si es un...
                    return TipoUsuario::usuarioRecepcionista(Yii::$app->user->identity->RolID);
                    //Llamada al m?todo que comprueba si es un administrador
                    //Retorno el metodo del modelo que comprueba el tipo de usuario que es por el rol (1,2,3,4) etc y que devuelve true o false
                }
                    ]
                ]
            ]
        ];
    }

    public function actions() {
        //Control de errores en caso de que se quiera acceder a las acciones de este controlador
        if (!Yii::$app->user->isGuest) {                                                                              //si el usuario esta logeado, o sea no es invitado
            if (Yii::$app->user->identity->RolID == 1) {                                                                //si el usuario es administrador
                Yii::$app->errorHandler->errorAction = 'agencia/error';                                               //se muestra la pantalla de error de agencia y su respectivo layout
            } elseif (Yii::$app->user->identity->RolID == 2) {
                Yii::$app->errorHandler->errorAction = 'recepcionista/error';
            } elseif (Yii::$app->user->identity->RolID == 3) {
                Yii::$app->errorHandler->errorAction = 'chofer/error';
            } elseif (Yii::$app->user->identity->RolID == 4) {
                Yii::$app->errorHandler->errorAction = 'cliente/error';
            } else {
                Yii::$app->errorHandler->errorAction = 'site/error';
            }
        } else {                                                                                                      //sino (si el usuario es invitado) se muestra la pagina de error del site
            Yii::$app->errorHandler->errorAction = 'site/error';
        }
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        return $this->redirect(['alta_viaje_manual']);
    }

    public function actionAlta_viaje_manual() {                      //renderiza el index de la carpeta agencia dentro de views
        $model = new AltaViajeManualModel();
        $model->setDataProvider();
        $model->setListChoferes();
        $model->setListVehiculos();
        $model->setTarifa();
        $info = $model->agenciaCoords();
        $canal = Yii::$app->user->identity->AgenciaID;
        if ($model->load(Yii::$app->request->post()) && ($model->registrarViaje() === true)) {
            Yii::$app->session->setFlash('viajeCreado');
            return $this->refresh();
        }
        return $this->render("altaViajeManual", ['model' => $model, 'info' => $info, 'canalAgencia' => $canal]);
    }

    public function actionActualizarviaje() {                      //renderiza el index de la carpeta agencia dentro de views
        $model = new ActualizarViajeModel();
        if (\Yii::$app->request->isPost) {
            $viajeSelected = Yii::$app->session['actualizar'];
            $model->setUpdateInfo($viajeSelected);
            if ($model->load(Yii::$app->request->post()) && ($model->actualizarViaje() === true)) {
                Yii::$app->session->setFlash('viajeActualizado', 'Viaje actualizado.');
                return $this->redirect(['listaviajes']);
            }
        } else {
            $model->setListChoferes();
            $model->setListVehiculos();
        }
        return $this->renderAjax("actualizarViaje", ['model' => $model]);
    }

    public function actionListaviajes() {                      //renderiza el index de la carpeta agencia dentro de views
        $model = new ListaSolicitudesServicioModel();
        $model->setDataProvider();
        if (\Yii::$app->request->isAjax) {
            if (\Yii::$app->request->isPost) {
                $selection = Yii::$app->request->post('keylist');
                $viajeSelected = $model->dataProvider->allModels[$selection];
                Yii::$app->session['actualizar'] = $viajeSelected; //CUANDO LA OPERACION ES ACTUALIZAR LE PASO LA SELECCION A LA OTRA VISTA (POPUP)
                switch (\Yii::$app->request->post('viajeoperacion')) { //TOMA EL VIAJEOPERACION QUE LE PASA EN EL DATA DEL AJAX
                    case 'cerrar':                                      //TOMA EL VALOR DEL VIAJEOPERACION SETEADO EN EL AJAX
                        $operacion = 3; //CERRAR
                        $model->ViajeOperacion($viajeSelected, $operacion);
                        Yii::$app->session['message'] = "Viaje cerrado correctamente"; //GUARDO EL MENSAJE FLASH Y LA OPERACION AQUI PARA UTILIZARLA ANTES DEL RENDER YA QUE DE LA FORMA NORMAL NO ME FUNCIONA EN ESTE CASO.
                        Yii::$app->session['operacion'] = "viajeCerrado";
                        break;
                    case 'cancelar':
                        $operacion = 2; //CANCELAR
                        $model->ViajeOperacion($viajeSelected, $operacion);
                        Yii::$app->session['message'] = "Viaje cancelado correctamente"; //GUARDO EL MENSAJE FLASH Y LA OPERACION AQUI PARA UTILIZARLA ANTES DEL RENDER YA QUE DE LA FORMA NORMAL NO ME FUNCIONA EN ESTE CASO.
                        Yii::$app->session['operacion'] = "viajeCancelado";
                        break;
                    case 'enviar':
                        $operacion = 0; //ENVIAR VIAJE
                        $model->ViajeOperacion($viajeSelected, $operacion);
                        Yii::$app->session['message'] = "Viaje enviado correctamente"; //GUARDO EL MENSAJE FLASH Y LA OPERACION AQUI PARA UTILIZARLA ANTES DEL RENDER YA QUE DE LA FORMA NORMAL NO ME FUNCIONA EN ESTE CASO.
                        Yii::$app->session['operacion'] = "viajeEnviado";
                        break;
                }
            }
        }
        Yii::$app->session->setFlash(Yii::$app->session['operacion'], Yii::$app->session['message']);
        return $this->render("listarSolicitudes", ['model' => $model]);
    }

    public function actionAutorizarsolicitud() {                      //renderiza el index de la carpeta agencia dentro de views
        $model = new AutorizarSolicitudModel();
        if (\Yii::$app->request->isPost) {
            $viajeSelected = Yii::$app->session['autorizar'];
            $model->setUpdateInfo($viajeSelected);
            if ($model->load(Yii::$app->request->post()) && ($model->autorizarSolicitud() === true)) {
                Yii::$app->session->setFlash('solicitudAutorizada', 'Solicitud autorizada.');
                Yii::$app->pusher->triggerEvent($viajeSelected['AgenciaID'], $viajeSelected['ClienteID'], 'Tu Remis Esta en Camino !');
                return $this->redirect(['listasolicitudes']);
            }
        } else {
            $model->setListChoferes();
            $model->setListVehiculos();
        }
        return $this->renderAjax("autorizarsolicitud", ['model' => $model]);
    }

    public function actionListasolicitudes() {
        $model = new ListaSolicitudesOnlineModel();
        $model->setDataProvider();
        if (\Yii::$app->request->isAjax) {
            if (\Yii::$app->request->isPost) {
                $selection = Yii::$app->request->post('keylist');
                $viajeSelected = $model->dataProvider->allModels[$selection];
                Yii::$app->session['autorizar'] = $viajeSelected; //CUANDO LA OPERACION ES ACTUALIZAR LE PASO LA SELECCION A LA OTRA VISTA (POPUP)
                switch (\Yii::$app->request->post('viajeoperacion')) { //TOMA EL VIAJEOPERACION QUE LE PASA EN EL DATA DEL AJAX
                    /* case 'cerrar':                                      //TOMA EL VALOR DEL VIAJEOPERACION SETEADO EN EL AJAX
                      $operacion = 3;//CERRAR
                      $model->ViajeOperacion($viajeSelected,$operacion);

mvc/views/recepcionista/altaViajeManual.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAssetRecepcionista;

use yii\grid\GridView;
use yii\helpers\BaseHtml;
use yii\widgets\ActiveForm;
use yii\bootstrap\Dropdown;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Button;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\web\JsExpression;
use yii\widgets\Pjax;
use kartik\select2\Select2;

AppAssetRecepcionista::register($this);
raoul2000\bootswatch\BootswatchAsset::$theme = 'superhero';
/* @var $this yii\web\View */
$this->title = 'RemisYa';
Modal::begin([
'header' => '<h4>Mensaje</h4>',
'id'=>'processmodal',
'size'=>'modal-sm',
'options'=>['class'=>'modal']
]);
echo "Procesando...";
Modal::end();

?>

<?php if (Yii::$app->session->hasFlash('viajeCreado')): ?>



<div class="alert alert-dismissible alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>Operacion exitosa!</strong>
    <a href="#" class="alert-link">Viaje creado correctamente</a>.
</div>
<?php endif ?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Administrador de Viajes</h4>
    </div>
    <div class="panel-body">
        <div class="row">

            <?php $form = ActiveForm::begin(); ?>
            <div class="col-lg-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Seleccione Origen y Destino: </h3>
                    </div>
                    <div class="panel-body">
                        <fieldset>
                            <?= $form->field($model, 'origenTexto')->input("text", ['id'=>'origenTexto','readonly' => true])->label("Origen"); ?>
                            <?= $form->field($model, 'origen')->hiddenInput(['id' => 'origencoordenada'])->label(false); ?>
                            <?= $form->field($model, 'destinoTexto')->input("text", ['id' => 'destinoTexto','readonly' => true])->label("Destino"); ?>
                            <?= $form->field($model, 'destino')->hiddenInput(['id' => 'destinocoordenada'])->label(false);?>
                            <div id="btn-bar">
                                <?=
                                $this->registerJs('$(document).ready(function () {
            $("#btn-ver-remiserias").on("click", function() {getRemiserias(true)});

            });', \yii\web\View::POS_READY);
                                $this->registerJs("var agenciaCoord = ". json_encode($info).";
var canal = ". json_encode($canalAgencia).";
 initializeCenteredMap(agenciaCoord);
 hearTheEvent(canal);",\yii\web\View::POS_READY);

                                ?>
                            </div>
                            <div id="mapHome">
                                <div id="map-Index">
                                    <div id="map"></div>
                                </div>
                                <input id="pac-input" class="controls" type="text" placeholder="Busca tu partido / barrio " />
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>Datos del viaje: </h3>
                    </div>
                    <div class="panel-body">
                        <fieldset>
                            <?=


                            $form->field($model, 'ClienteID')->widget(Select2::classname(), [
    'options' => ['placeholder' => 'Buscar un cliente...'],
    'language' => 'es',
    'pluginOptions' => [
    'allowClear' => true,
    'minimumInputLength' => 3,
    'ajax' => [
        'url' => Url::to(['recepcionista/clienteslist']),
        'dataType' => 'json',
        'data' => new JsExpression('function(params) { return {q:params.term}; }')
    ],
    'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
    'templateResult' => new JsExpression('function(cliente) { return cliente.text; }'),
    'templateSelection' => new JsExpression('function (cliente) { return cliente.text; }'),
],
])->label("Cliente");
                            ?>
                            <div class="row">
                                <div class="col-md-4">
                                    <?= $form->field($model, 'Distancia')->input("text", ['id'=>'distancia','maxlength' => '50','readonly' => true])->label("Distancia"); ?>
                                </div>
                                <div class="col-md-8">
                                    <div class="form-group">
                                        <label class="control-label">Tarifa automatica x Km</label>
                                        <div class="input-group">
                                            <span class="input-group-addon" style="background-color:#2b3e50">$</span>
                                            <?= Html::input('text', 'PrecioKM', $model->PrecioKM, ['class' => 'form-control','id'=>'precioKM']) ?>

                                            <span class="input-group-btn">
                                                <?=
                                                Html::button('Calcular', ['class'=>'btn btn-primary', 'onclick' => '$("#importetotal").val((($("#precioKM").val())*($("#distancia").val().replace(" Km",""))).toFixed(0) + " $");'])
                                                ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?= $form->field($model, 'ImporteTotal')->input("text", ['maxlength' => '50','id' => 'importetotal'])->label("Importe aproximado"); ?>
                            <?= $form->field($model, 'Chofer')->dropDownList($model->Choferes,['prompt'=>'Seleccione chofer'])?>
                            <?= $form->field($model, 'Vehiculo')->dropDownList($model->Vehiculos,['prompt'=>'Seleccione vehiculo'])?>
                            <div class="row">
                                <div class="col-md-6">
                                    <?= $form->field($model, 'CanalVenta')->dropDownList([1 => 'Telefonico', 2 => 'Personal'],['options' => [ 2 => ['selected ' => true]]])->label("Canal de venta") ?>
                                </div>
                                <div class="col-md-6">
                                    <?= $form->field($model, 'TipoViaje')->dropDownList([0 => 'Viaje Normal', 4 => 'Reserva'],['options' => [ 0 => ['selected ' => true]]])->label("Tipo de viaje") ?>
                                </div>
                            </div>
                            <?= $form->field($model, 'Comentario')->textArea(['rows' => '4']) ?>
                            <?= Html::submitButton('Crear Viaje', ['class' => 'btn btn-lg btn-primary','onclick'=>'$("#processmodal").modal("show");$.post( "'.Url::to(['recepcionista/alta_viaje_manual']).'", function() {$("#processmodal").modal("hide");});']); ?>
                            <?= Html::a('Ver Viajes', ['/recepcionista/listaviajes'], ['class'=>'btn btn-lg btn-primary']) ?>
                            <?= Html::a('Ver Solicitudes', ['/recepcionista/listasolicitudes'], ['class'=>'btn btn-lg btn-primary']) ?>
                        </fieldset>
                    </div>
                </div>

            </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

mvc/views/recepcionista/listaSolicitudesOnline.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAssetRecepcionista;
use yii\grid\GridView;
use yii\helpers\BaseHtml;
use yii\widgets\ActiveForm;
use yii\bootstrap\Dropdown;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Button;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\bootstrap\Alert;
raoul2000\bootswatch\BootswatchAsset::$theme = 'superhero';
AppAssetRecepcionista::register($this);
$this->title = 'RemisYa';

?>
<?php
Modal::begin([
'header' => '
        <h4>Mensaje</h4>',
'id'=>'solicitudes_processmodal',
'size'=>'modal-sm',
'options'=>['class'=>'modal'],
'clientOptions' => ['backdrop' => 'static', 'keyboard' => false]
]);
echo "Procesando...";
Modal::end();
?>
<?php
Modal::begin([
'id' => 'solicitudes_modal',
'size' => 'modal-sm',
]);
echo "<div id='modalContent'></div>";
Modal::end();
?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Listado de solicitudes online</h4>
    </div>
    <div class="panel-body">

        <?php Pjax::begin(['id'=>'solicitudes_containerpjax','timeout' => false]); ?>
        <?php if (Yii::$app->session->hasFlash('solicitudAutorizada')): ?>
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">X</button>
            <h4>
                <i class="icon fa fa-check"></i>Operacion realizada.
            </h4>
            <?= Yii::$app->session->getFlash('solicitudAutorizada') ?>
        </div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('solicitudRechazada')): ?>
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">X</button>
            <h4>
                <i class="icon fa fa-check"></i>Operacion realizada.
            </h4>
            <?= Yii::$app->session->getFlash('solicitudRechazada') ?>
        </div>
        <?php endif; ?>
        <?php $form = ActiveForm::begin(['options' => ['data-pjax' => true]]);?>
        <div class="table-responsive">
            <?=
            GridView::widget([
            'id' => 'solicitudes_grid',
            'summary'=>'',
            'dataProvider' => $model->dataProvider,
            'tableOptions' => ['class' => 'table table-bordered table-hover', 'style'=>'border-collapse: collapse; border: 3px solid #df691a; '],
            'columns' => [
                ['header' => '<h5>Cliente</h5>','attribute' => 'ClienteNombre','contentOptions' => ['style'=>'border-color:black;'],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Destino</h5>','attribute' => 'DestinoDireccion','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Chofer</h5>','attribute' => 'ChoferNombre','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Marca</h5>','attribute' => 'VehiculoMarca','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Modelo</h5>','attribute' => 'VehiculoModelo','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Tipo de viaje</h5>','attribute' => 'ViajeTipo','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Estado</h5>','attribute' => 'Estado','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
            ],
            'rowOptions' => function ($model, $key, $index, $grid) {
                return ['rowid' => $key, 'onclick' => '$(this).addClass("success").siblings().removeClass("success");','style' => 'cursor:pointer'];
            },
      ]);
            ?>
        </div>

        <?php ActiveForm::end(); ?>
        <?php Pjax::end(); ?>
        <div id="solicitudesbuttonsOperaciones">
            <?= Html::button('Autorizar solicitud',['value' => Url::toRoute('recepcionista/autorizarsolicitud'), 'class' => 'btn btn-lg btn-primary', 'id' => 'autorizarButton','operacion'=>'autorizar',]);?>
            <?= Html::button('Rechazar solicitud',['value' => Url::toRoute('recepcionista/listasolicitudes'),'class' => 'btn btn-lg btn-primary','name'=>'submit','operacion'=>'rechazar']);?>
        </div>
    </div>
</div>

mvc/views/recepcionista/listarSolicitudes.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAssetRecepcionista;
use yii\grid\GridView;
use yii\helpers\BaseHtml;
use yii\widgets\ActiveForm;
use yii\bootstrap\Dropdown;
use yii\helpers\ArrayHelper;
use yii\bootstrap\Button;
use yii\bootstrap\Modal;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\bootstrap\Alert;
raoul2000\bootswatch\BootswatchAsset::$theme = 'superhero';
AppAssetRecepcionista::register($this);
$this->title = 'RemisYa';

?>
<?php
Modal::begin([
'header' => '
        <h4>Mensaje</h4>',
'id'=>'processmodal',
'size'=>'modal-sm',
'options'=>['class'=>'modal'],
'clientOptions' => ['backdrop' => 'static', 'keyboard' => false]
]);
echo "Procesando...";
Modal::end();
?>
<?php
Modal::begin([
'id' => 'modal',
'size' => 'modal-sm',
]);
echo "<div id='modalContent'></div>";
Modal::end();
?>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h4 class="panel-title">Listado de viajes emitidos</h4>
    </div>
    <div class="panel-body">

        <?php Pjax::begin(['id'=>'containerpjax','timeout' => false]); ?>
        <?php if (Yii::$app->session->hasFlash('viajeActualizado')): ?>
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">X</button>
            <h4>
                <i class="icon fa fa-check"></i>Operacion realizada.
            </h4>
            <?= Yii::$app->session->getFlash('viajeActualizado') ?>
        </div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('viajeCerrado')): ?>
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">X</button>
            <h4>
                <i class="icon fa fa-check"></i>Operacion realizada.
            </h4>
            <?= Yii::$app->session->getFlash('viajeCerrado') ?>
        </div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('viajeCancelado')): ?>
        <div class="alert alert-success alert-dismissable">
            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">X</button>
            <h4>
                <i class="icon fa fa-check"></i>Operacion realizada.
            </h4>
            <?= Yii::$app->session->getFlash('viajeCancelado') ?>
        </div>
        <?php endif; ?>
        <?php $form = ActiveForm::begin(['options' => ['data-pjax' => true]]);?>
        <div class="table-responsive">
            <?=
            GridView::widget([
            'id' => 'viajes_grid',
            'summary'=>'',
            'dataProvider' => $model->dataProvider,
            'tableOptions' => ['class' => 'table table-bordered table-hover', 'style'=>'border-collapse: collapse; border: 3px solid #df691a; '],
            'columns' => [
                ['header' => '<h5>Cliente</h5>','attribute' => 'ClienteNombre','contentOptions' => ['style'=>'border-color:black;'],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Destino</h5>','attribute' => 'DestinoDireccion','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Chofer</h5>','attribute' => 'ChoferNombre','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Marca</h5>','attribute' => 'VehiculoMarca','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Modelo</h5>','attribute' => 'VehiculoModelo','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Canal</h5>','attribute' => 'ViajeTipo','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
                ['header' => '<h5>Estado</h5>','attribute' => 'Estado','contentOptions' => ['style'=>'border-color:black;',],'headerOptions' => ['style'=>'border-color:black;background-color:#df691a;']],
            ],
            'rowOptions' => function ($model, $key, $index, $grid) {
                return ['rowid' => $key, 'onclick' => '$(this).addClass("success").siblings().removeClass("success");','style' => 'cursor:pointer'];
            },
      ]);
            ?>
        </div>

        <?php ActiveForm::end(); ?>
        <?php Pjax::end(); ?>
        <div id="buttonsOperaciones">
            <?= Html::button('Cerrar',['value' => Url::toRoute('recepcionista/listaviajes'),'class' => 'btn btn-lg btn-primary','name'=>'submit','operacion'=>'cerrar']);?>
            <?= Html::button('Cancelar',['value' => Url::toRoute('recepcionista/listaviajes'),'class' => 'btn btn-lg btn-primary','name'=>'submit','operacion'=>'cancelar']);?>
            <?= Html::button('Actualizar',['value' => Url::toRoute('recepcionista/actualizarviaje'), 'class' => 'btn btn-lg btn-primary', 'id' => 'actualizarButton','operacion'=>'actualizar',]);?>
            <?= Html::button('Enviar',['value' => Url::toRoute('recepcionista/listaviajes'),'class' => 'btn btn-lg btn-primary','name'=>'submit','operacion'=>'enviar']);?>
        </div>
    </div>
</div>